### ISSUE TITLE
ModerPerl  Highlight problem

### ISSUE THREAD

**Issue by KES777** [Blaizer/ModernPerl-sublime#15] opened 2015-03-09 14:12 UTC
In this plugin next problems:

if( defined $a  &&  $a <=> $b ); 

1. variables are not recognized
2. comparison operator is not recognized
3. 'defined' is not mutched as 'support.function.perl'
4. && is not mutched at all

**Comment by Blaizer** [comment] 2015-03-20 04:23
`defined` is not a function, if you knew Perl well enough you'd know it's actually an operator, so I highlight it as a keyword. It's set to `keyword.other.function.perl`. Variables are recognised, they're just deliberately set to something that isn't coloured by any themes: `punctuation.definition.var.perl`. You can add that to your theme if you want. Punctuation operators aren't recognised, indeed, but this is the same as the original Perl syntax. I think it looks fine to just leave them uncoloured.

None of the things you mentioned are bugs, it's all working as intended. I'm closing this.

**Closed by Blaizer** 2015-03-20 04:23 UTC
